weights: weights/yolov5s.pt
cfg: models/yolov5s_fire_detect.yaml
data: data/voc_fire_detect.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 120
batch_size: 32
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 4
project: runs/train
entity: null
name: fire_detect-yolov5s
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
save_dir: runs\train\fire_detect-yolov5s2
